### ISSUE TITLE
Doesn't load

### ISSUE THREAD

**Issue by ghost** [WobLight/QuestHaste#1]
Doesn't load. I installed /Interface/AddOns folder like other ones, i can't see on the list. It doesn't say anything like 'outdated,etc'. 1.12.-enGB client

**Comment by WobLight** [comment]
Is it present in the addons list? If not, make sure the folder in AddOns is named QuestHaste and that QuestHaste.toc is inside it (not in any further subfolder).
If it is present in the addon list, be sure to read README, the addon does nothing by default, you have to activate it using modifier keys (Control, Alt, Shift) while opening quest dialogs or clicking on quest gossips and so on.
